apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stocksim

resources:
  - ../../base
  - marketfeed-ingress.yaml
  - rabbitmq-secret.yaml
  - toolbox.yaml

images:
  - name: stocksim/marketfeed
    newTag: local

patches:
  - target:
      kind: Deployment
      name: marketfeed
    path: marketfeed-patch.yaml
