apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketfeed
spec:
  ingressClassName: traefik
  rules:
    - host: marketfeed.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: marketfeed
                port:
                  number: 80
