apiVersion: v1
kind: Secret
metadata:
  name: stocksim-connectionstrings
type: Opaque
stringData:
  AuthDb: "Host=postgres;Port=5432;Database=authdb;Username=CHANGE_ME;Password=CHANGE_ME"
  TradingDb: "Host=postgres;Port=5432;Database=tradingdb;Username=CHANGE_ME;Password=CHANGE_ME"
  PortfolioDb: "Host=postgres;Port=5432;Database=portfoliodb;Username=CHANGE_ME;Password=CHANGE_ME"
