apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketfeed
  labels:
    app.kubernetes.io/name: marketfeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: marketfeed
  template:
    metadata:
      labels:
        app.kubernetes.io/name: marketfeed
    spec:
      containers:
        - name: marketfeed
          image: stocksim/marketfeed
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otelcol.observability:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
