apiVersion: v1
kind: Service
metadata:
  name: marketfeed
  labels:
    app.kubernetes.io/name: marketfeed
    app.kubernetes.io/part-of: stocksim
spec:
  selector:
    app.kubernetes.io/name: marketfeed
  ports:
    - name: http
      port: 80
      targetPort: http
