apiVersion: v1
kind: Service
metadata:
  name: otelcol
  labels:
    app.kubernetes.io/name: otelcol
spec:
  selector:
    app.kubernetes.io/name: otelcol
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: prom-exp
      port: 9464
      targetPort: prom-exp
    - name: otel-metrics
      port: 8888
      targetPort: otel-metrics
