apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app.kubernetes.io/name: zipkin
spec:
  selector:
    app.kubernetes.io/name: zipkin
  ports:
    - name: http
      port: 9411
      targetPort: http
