apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - marketfeed
  - rabbitmq
  - web
  - postgres
  - portfolio-worker
  - trading-worker

labels:
  - pairs:
      app.kubernetes.io/part-of: stocksim
    includeTemplates: true
    includeSelectors: false
