apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - marketfeed/deployment.yaml
  - marketfeed/service.yaml
  - rabbitmq/deployment.yaml
  - rabbitmq/service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: stocksim