apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - marketfeed/deployment.yaml
  - marketfeed/service.yaml
  - rabbitmq/deployment.yaml
  - rabbitmq/service.yaml
  - web/deployment.yaml
  - web/service.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - postgres/init-job.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: stocksim