global:
  scrape_interval: 5s

scrape_configs:  
  - job_name: 'otelcol'
    static_configs:
      - targets: ['otelcol:9464']
  - job_name: "otelcol-internal"
    static_configs:
      - targets: ["otelcol:8888"]
