apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
    spec:
      containers:
        - name: web
          image: stocksim/web
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otelcol.observability:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: Rabbit__Host
              value: "rabbitmq"
            - name: Rabbit__User
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-auth
                  key: username
            - name: Rabbit__Pass
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-auth
                  key: password
            - name: ConnectionStrings__AuthDb
              valueFrom:
                secretKeyRef:
                  name: stocksim-connectionstrings
                  key: AuthDb
            - name: ConnectionStrings__TradingDb
              valueFrom:
                secretKeyRef:
                  name: stocksim-connectionstrings
                  key: TradingDb
            - name: ConnectionStrings__PortfolioDb
              valueFrom:
                secretKeyRef:
                  name: stocksim-connectionstrings
                  key: PortfolioDb
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
